/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiStatusRouteImport } from './routes/api-status'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as HistoricalDataRouteImport } from './routes/historical-data'
import { Route as ModelPerformanceRouteImport } from './routes/model-performance'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockAnalysisRouteImport } from './routes/stock-analysis'
import { Route as VisualizationsRouteImport } from './routes/visualizations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api-status',
  path: '/api-status',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalDataRoute = HistoricalDataRouteImport.update({
  id: '/historical-data',
  path: '/historical-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPerformanceRoute = ModelPerformanceRouteImport.update({
  id: '/model-performance',
  path: '/model-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAnalysisRoute = StockAnalysisRouteImport.update({
  id: '/stock-analysis',
  path: '/stock-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationsRoute = VisualizationsRouteImport.update({
  id: '/visualizations',
  path: '/visualizations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-status': typeof ApiStatusRoute
  '/compare': typeof CompareRoute
  '/historical-data': typeof HistoricalDataRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/prediction': typeof PredictionRoute
  '/settings': typeof SettingsRoute
  '/stock-analysis': typeof StockAnalysisRoute
  '/visualizations': typeof VisualizationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-status': typeof ApiStatusRoute
  '/compare': typeof CompareRoute
  '/historical-data': typeof HistoricalDataRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/prediction': typeof PredictionRoute
  '/settings': typeof SettingsRoute
  '/stock-analysis': typeof StockAnalysisRoute
  '/visualizations': typeof VisualizationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-status': typeof ApiStatusRoute
  '/compare': typeof CompareRoute
  '/historical-data': typeof HistoricalDataRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/prediction': typeof PredictionRoute
  '/settings': typeof SettingsRoute
  '/stock-analysis': typeof StockAnalysisRoute
  '/visualizations': typeof VisualizationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-status'
    | '/compare'
    | '/historical-data'
    | '/model-performance'
    | '/prediction'
    | '/settings'
    | '/stock-analysis'
    | '/visualizations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-status'
    | '/compare'
    | '/historical-data'
    | '/model-performance'
    | '/prediction'
    | '/settings'
    | '/stock-analysis'
    | '/visualizations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-status'
    | '/compare'
    | '/historical-data'
    | '/model-performance'
    | '/prediction'
    | '/settings'
    | '/stock-analysis'
    | '/visualizations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiStatusRoute: typeof ApiStatusRoute
  CompareRoute: typeof CompareRoute
  HistoricalDataRoute: typeof HistoricalDataRoute
  ModelPerformanceRoute: typeof ModelPerformanceRoute
  PredictionRoute: typeof PredictionRoute
  SettingsRoute: typeof SettingsRoute
  StockAnalysisRoute: typeof StockAnalysisRoute
  VisualizationsRoute: typeof VisualizationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-status': {
      id: '/api-status'
      path: '/api-status'
      fullPath: '/api-status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical-data': {
      id: '/historical-data'
      path: '/historical-data'
      fullPath: '/historical-data'
      preLoaderRoute: typeof HistoricalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-performance': {
      id: '/model-performance'
      path: '/model-performance'
      fullPath: '/model-performance'
      preLoaderRoute: typeof ModelPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-analysis': {
      id: '/stock-analysis'
      path: '/stock-analysis'
      fullPath: '/stock-analysis'
      preLoaderRoute: typeof StockAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizations': {
      id: '/visualizations'
      path: '/visualizations'
      fullPath: '/visualizations'
      preLoaderRoute: typeof VisualizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiStatusRoute: ApiStatusRoute,
  CompareRoute: CompareRoute,
  HistoricalDataRoute: HistoricalDataRoute,
  ModelPerformanceRoute: ModelPerformanceRoute,
  PredictionRoute: PredictionRoute,
  SettingsRoute: SettingsRoute,
  StockAnalysisRoute: StockAnalysisRoute,
  VisualizationsRoute: VisualizationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
